sambacc/commands/ctdb.py, sambacc/ctdb.py, tests/test_ctdb.py
The pod that acts as a CTDB node may be migrated/restarted/or otherwise change IP address. Tweaking our approach to populating the nodes file we can update the CTDB cluster to use the node with it's new address.
Please review by 2021-09-09
=> support moving ctdb enabled pods to new addresses

tests/container/build.sh
Minor improvement to hide the following advice:
_Cloning into '/var/tmp/build/sambacc'...
Note: switching to 'e3e2a53bea5d'. You are in 'detached HEAD' state._
=> Git checkout to a branch to avoid detached HEAD

sambacc/commands/run.py, sambacc/samba_cmds.py
See sub-section **_Duplicates in command line utils_** under _Improved command line user experience_ from [v4.15 release notes](https://www.samba.org/samba/history/samba-4.15.0.html)
=> Add support for new/replaced winbindd cli option `--debug-stdout`

sambacc/commands/cli.py, sambacc/commands/dns.py, sambacc/ctdb.py, sambacc/leader.py, tests/container/Containerfile, tests/test_ctdb.py
In some cases certain operations should only be handled by one "node" in a cluster. In the case of a samba container we want to prevent all the nodes in a cluster from submitting DNS registration when the state file changes, and only have the current leader handle the submission.
These changes add general infrastructure for determining a leader and then uses it to limit registration when ctdb is enabled.
=> only send dns registrations when run on "leader" node

sambacc/commands/cli.py, sambacc/commands/ctdb.py, sambacc/commands/initialize.py, sambacc/join.py
In many cases, logging is preferable to simple print calls.
These patches replace some obvious cases where logging is better than prints.
=> Replace some print calls with logging

sambacc/samba_cmds.py, tests/test_samba_cmds.py
Fixes: #22
The main point for the PR is to fix the issue where ltdbtool fails when run with samba's standard approach for setting debug level on the cli. This tool is very simple and low level and thus is not built to accept that option. 
To make this change I factored a new base class out of SambaCommand and made our ltdbtool wrapper based on that.
While I was in the neighborhood I added tests for the new class as well some of the previously uncovered functions in samba_cmds.
=> do not try to enable debugging for ldbtool

examples/addc.json, sambacc/addc.py, sambacc/commands/addc.py, sambacc/commands/dcmain.py, sambacc/config.py, sambacc/samba_cmds.py, setup.cfg, tests/test_config.py, tox.ini
While it's a bit rough and simplistic, these changes add AD DC support to sambacc. Currently, there's one new script `samba-dc-container` that supports one subcommand `run`. It also has setup actions for `provision` and `join` and can also wait for the domain to appear with `wait-domain` which will poll until the ldap srv record exists for the domain.
With this sambacc supports (by default) the same behavior as the hard-coded scripts in samba-container's ad-server container image. In addition, you can customize your domain and initial users through the sambacc config json. You can then join additional containers to the domain.
I probably could have added more unit tests but the layer between us and samba-tool is thin currently. In the future, some of the stuff like user and groups …
=> Initial AD DC Support

sambacc/samba_cmds.py, tests/test_samba_cmds.py
Fixes: #31
The issue was specific to uses of the CommandArgs when used with the execute call.
=> fix command prefixes when used with exec

sambacc/commands/cli.py, sambacc/commands/config.py, sambacc/commands/initialize.py, sambacc/config.py, sambacc/permissions.py, tests/container/Containerfile, tests/test_commands_config.py, tests/test_config.py, tests/test_permissions.py, tox.ini
These patches add general support for choosing and configuring a "permissions handler". Currently our handlers are very simple and allow setting permissions once, always, or never (none=no-op).
Then, in the code paths recently added to ensure share dirs exist we add lines to invoke the permissions handler. In most scenarios this means that the first time this code is called the permissions will be set. On subsequent calls the code will see the status xattr is set and skip changing the perms. As noted above, this is configurable.
=> Add permissions handling to sambacc

sambacc/_xattr.py, sambacc/permissions.py, tests/container/Containerfile, tests/container/build.sh, tests/test_permissions.py, tox.ini
Fedora 34 is no longer supported with the recent release of F 36. 
With python 3.9 no longer being the "native" version of python I had to juggle a few things wrt to the tox test environments. We want to continue testing with python 3.9 in case we want to also support centos/rhel 9.
So we end up needing runs specifcically for py39 and some for whatever the system version of python is that can pull in native packaged libs like samba/inotify/xattr/etc.
This work is also a stepping stone to building an RPM so that the samba-container images can be "fully" RPMized and we can have a single source of truth for system python package deps (here in sambacc).
=> Update base container image to fedora 35

.github/workflows/ci.yml
Copy and pasted from the yaml file in samba-containers, so I assume its good. :-)
Signed-off-by: John Mulligan <jmulligan@redhat.com>
=> workflows: fix pushing to registry on sched builds

pyproject.toml, sambacc/addc.py, sambacc/commands/cli.py, sambacc/commands/config.py, sambacc/commands/dcmain.py, sambacc/commands/dns.py, sambacc/commands/initialize.py, sambacc/commands/join.py, sambacc/commands/main.py, sambacc/config.py, sambacc/container_dns.py, sambacc/ctdb.py, sambacc/inotify_waiter.py, sambacc/join.py, sambacc/leader.py, sambacc/netcmd_loader.py, sambacc/samba_cmds.py, sambacc/typelets.py
To improve the type annotations usage in sambacc and hopefully catch more errors early the first step is to enable the option "disallow_incomplete_defs" in mypy. This disallows mixing typed and untyped parameters and return types on a single function call. It does not affect a function that has no annotations at all.
The first set of commits adds annotations to many parts of the code base. Then we enable the option in mypy to enforce it in the future (via pyproject.toml). Finally, we update a few straggling uses of typing.List and typing.Dict to the 'list' and 'dict' equivalents since our minimum version is python3.9.
=> More type annotations

tests/container/Containerfile
Expects Fedora36 to be maintained until mid 2023.
Use full image name, same as in 'samba-container' images.
Signed-off-by: Shachar Sharon <ssharon@redhat.com>
=> container: bump base image to fedora36

sambacc/ctdb.py, sambacc/samba_cmds.py, tests/test_ctdb.py
With Samba [v4.16](https://www.samba.org/samba/history/samba-4.16.0.html), `recmaster` administrative sub-command for `ctdb` was renamed to `leader`. Therefore we make use of already existing mechanism to detect the presence of `leader` admin command and execute it for determining the leader node.
=> Use newly replaced `leader` admin command for `ctdb`

pyproject.toml, sambacc/config.py, sambacc/container_dns.py, sambacc/ctdb.py, sambacc/inotify_waiter.py, sambacc/jfile.py, sambacc/join.py, sambacc/netcmd_loader.py, sambacc/nsswitch_loader.py, sambacc/passdb_loader.py, sambacc/passwd_loader.py, sambacc/permissions.py, sambacc/samba_cmds.py, sambacc/simple_waiter.py, tests/test_container_dns.py
The sambacc dir is basically a library and we want to ensure high quality and good documentation so configure mypy to require
type annotations on functions defined in sambacc. Update code in sambacc to add type annotations to any functions lacking them.
The sambacc.commands on the other hand are mean to be only run as part of our CLI tools so we'll be a bit less strict there.
=> sambacc: complete type annotations

tox.ini
Rework how the tox.ini file is organized in order to remove a `command found but not installed in testenv` when running tox. We currently need at least one test run to be executed with system site packages enabled, but we don't need it that way for mypy.
=> tox.ini: avoid one tox warning when running py3-mypy

sambacc/commands/config.py
Latest black version (23.1a1) requires extra empty line after one-liner comment. This, in turn, causes samba-container CI to fail.
Signed-off-by: Shachar Sharon <ssharon@redhat.com>
=> sambacc: re-format with black version 23.1a1

tests/container/Containerfile
This reverts commit af63900e4a0f2cef025656a7242c2cdda73fc845.
This should fix the current failures in samba-containers, allowing us to have a more in-depth discussion of what the right way forward is.
Signed-off-by: John Mulligan <jmulligan@redhat.com>
=> Revert "container: Switch to CentOS Stream 9 as base image"

tests/container/Containerfile, tests/container/build.sh
Right now, sambacc and samba-containers is in a pretty awkward situation. The base oses for the images are different and we're building RPMs that have the wrong ABI for the samba-container images. 
These changes pull nearly all the logic out of the continerfile and into build.sh so that it is easier to build and test and varying base OSes. If this is merged we have the ability to create multi-stage builds in samba-containers project hat pretty much only need to consume sambacc's container image OR even simply drop that and do something like curl build.sh from sambacc's github repo. Regardless of how we use it in the samba-containers repo I think this is helpful step to get out of a bad sitation and gain flexibility when executing tests.
----
This now makes it possible to more easily test …
=> container: self contained build script

.github/mergify.yml
In samba-operator we updated the mergify rules to label PRs that are "old", applying a "priority-review" label to the PR.  See the samba-operator commit d2e55778920d3ab0bfd9c7f820fe5b1f2b9de4e4 for full details.
=> github: sync mergify rules that handle aged PRs

MANIFEST.in, pyproject.toml, sambacc/commands/cli.py, sambacc/commands/config.py, sambacc/commands/main.py, sambacc/config.py, sambacc/schema/conf-v0.schema.json, sambacc/schema/conf-v0.schema.yaml, sambacc/schema/conf_v0_schema.py, sambacc/schema/tool.py, tests/test_commands_config.py, tests/test_config.py, tox.ini
Fixes: #67 
Add [jsonschema](http://json-schema.org) support to sambacc.  We add a new subdir `sambacc/schema` that holds the canonical YAML schema files and generated files derived from the YAML sources.
A new tool that can be invoked on the cli by `python -m sambacc.schema.tool` is added to help manage the schema files and ensure they are kept in sync.
The sambacc.config module is updated to take advantage to schema based validation when the python jsonschema library is available. On the CLI one can request automatic validation (validate if library is present) or require or disable validation. The `auto` option is the default.
Since this PR is already long-ish I'm avoiding two things:
* Trying to cover all cases in the schema. I'm sure that there are gaps. This builds the infra and we …
=> Add json schema support for validating the configuration

.github/workflows/ci.yml, sambacc/config.py, setup.cfg, tests/container/build.sh, tox.ini
Upon merging #69 the samba-container builds broke. 
The RPM build failed because the tox test dependencies listed jsonschema and no jsonschema python packages were installed. On top of that, the python3-jsonschema package in fedora 36 is incompatible and breaks the tests. So we're mostly just undoing the initial damage to try and get samba-containers working again.
To prevent future damage this PR enables the CI to run the RPM build step which was previously skipped (and only executed by samba-container builds).
=> fix rpm build issues introduced by jsonschema feature

.github/workflows/ci.yml
Depends on: #74 
Adds additional test runs using centos stream 9 and fedora 37 base images.
Also adds a change not to run 'push' job unless 'test' succeeds
=> Add more distros to CI test runs

extras/python-sambacc.spec, setup.cfg, tox.ini
Depends on: #76 
This PR is a bit of a grab bag of stuff but the main point is to disentangle the test environments "normally" used by tox and when we include system packages (AKA site packages).
Thus the "py<N>" packages will *always* use the isolated virtualenvs and the new "py3-sys" environment will use site packages.
This then adapts the rpm spec to use the new env, fixes a warning, and also teaches tox about our first optional dependency specified as an extra.
=> tox: add a distinct test env for system packages

.copr/Makefile, extras/python-sambacc.spec, sambacc/config.py, tests/container/build.sh
Depends on: #77 
Another grab bag of changes that work up to getting basic support for COPR in place.
Prepare sambacc and the rpm spec file for optional dependencies.
Fix the rpm spec generation to work correctly outside our container env.
Make the build.sh script flexible enough to be reused in the COPR environment. Add a .copr/Makefile for the COPR system to build SRPMs directly from the git checkout.
=> Add initial support for building sambacc rpms via COPR

docs/configuration.md, extras/python-sambacc.spec, sambacc/config.py, setup.cfg, tests/test_config.py, tox.ini
Depends on: #69 
JSON is great in that it is standardized, tons of languages support it, and it's pretty simple to parse and work with. It is pretty terrible to edit by hand though. This PR adds support for both TOML and YAML as formats for our sambacc configuration.  The intent here is to make writing a config by hand simpler and thus using samba-container directly without management by the operator, for example, easier.
TOML is probably the nicest to work with once you memorize the rules around brackets (tables vs. arrays of tables).  This module is included in python, however, the python version must be 3.11 or later.
YAML is a superset of JSON that is much easier to write and is extremely popular, if a bit over-complicated.
The file format to use is selected based on the file name's …
=> Add support for config files in TOML and YAML formats

.gitlint
Ignore lines that start like `[1]: ` or `[2] ` such that we can have long text like URLs in the commits without triggering other gitlint body rules.
Copied from the same changes already made in samba-container (PR samba-in-kubernetes/samba-container#150).
=> gitlint: ignore body lines that are footnotes

sambacc/addc.py, sambacc/commands/addc.py, sambacc/commands/cli.py, sambacc/config.py, sambacc/smbconf_api.py, sambacc/smbconf_samba.py, tests/container/Containerfile, tests/test_addc.py, tests/test_smbconf_api.py, tests/test_smbconf_samba.py, tox.ini
This revisits and reuses parts of the work done in #45
Fixes: #43 
When replying to samba-in-kubernetes/samba-container#154 I realized that one of the workarounds I suggested could be implemented in sambacc without too many complications and without needing to change `samba-tool`. Also, all versions of samba used by samba-container images that provide AD DC images should be providing the smbconf python library now. This avoids us having to parse smb.conf-style-ini in python.
Briefly, when an AD DC configuration provides globals references the global options are passed directory to samba-tool commands and after samba-tool has generated an smb.conf, sambacc uses smbconf libraries to read the smb.conf, merge the settings from the sambacc globals and write out an updated smb.conf file.
An …
=> add support for custom global options in AD DC confgurations

README.md
Fix links for `samba-container project` and `COPR repository` because I messed up the markdown syntax previously.
=> readme: fix mixed up mark down links

docs/configuration.md
Just clarify what types each configuration section key expects.
=> docs: be clearer about what types top-level configs take

docs/release-process.md
The PyPI sambacc repo is mainly a "space saver" to reserve the name, however it's best to keep it up to date and so the doc shouldn't make you guess as to the url for the repo.
=> docs: add a link to the pypi repository for sambacc to release doc

setup.cfg
Fix the `twine check` errors and missing text on pypi for sambacc.
=> setup.cfg: fix missing description text

sambacc/commands/config.py, tests/test_commands_config.py
Fix issue using remote resources in update-config command by passing the opener to read_config_files call.
=> commands: pass opener to read_config_files called from update-config

sambacc/rados_opener.py, tests/test_rados_opener.py
There are cases where certain configuration items may not be stored in the Ceph cluster's  rados pool but rather in the Ceph MON's configuration key store. This can be accessed via a mon command. Add support for new pseudo uri's formed like:
rados:mon-config-key:foo/bar/baz
Instead of fetching an item from a rados pool, this will try to fetch a key in a manner equivalent to running the following CLI command:
`ceph config-key get foo/bar/baz`
This idea is borrowed from the ceph iscsi support.
=> sambacc: extend rados pseudo-uris to include getting mon config keys

sambacc/commands/main.py, sambacc/rados_opener.py, tests/test_rados_opener.py, tox.ini
Add a command line option --ceph-id and environment variable SAMBACC_CEPH_ID that allow one to specify the user/id/entity name (ceph is really inconsistent about what to call these IMO) that should be used to read the config. Annoyingly, ceph libraries default to using the admin user with maximum capabilities and so it's critical to remember to get this working for non-admin users - as this PR tries to do. 
The value provided to --ceph-id / SAMBACC_CEPH_ID can be either just the name string (like: `bob` or `client.bob`) or a key value pair like `name=client.bob`. The former is implemented for convenience but ceph tooling can be a bit ambiguous about if it expects/provides the prefixed (`client.`) or unprefixed form of names. The key-value form allows one to more precisely state if the …
=> sambacc: add support for selecting ceph auth user/entity/id when reading config

sambacc/commands/config.py, sambacc/commands/ctdb.py, sambacc/commands/dns.py, sambacc/commands/main.py, tox.ini
The CI was failing recently due to is (somehow) using the black 24 alpha. This was hackily fixed in PR #98 and this PR more cleanly pins the project to use black's 2023 style for now.
I did find some obvious cleanups using the --preview (2024) style and took them in the other change in this pr. However, I'm not planning to commit to the 2024 style until understand better why it is "messing up" some of the protocol function definitions.
=> explicitly use black version from 2023

tox.ini
Run `tox -e schemaupdate` to regenerate the schema file(s).
This complements the existing read-only schemacheck environment with a read-write env.
=> tox.ini: add schemaupdate environment

docs/configuration.md, sambacc/addc.py, sambacc/commands/addc.py, sambacc/config.py, sambacc/schema/conf-v0.schema.json, sambacc/schema/conf-v0.schema.yaml, sambacc/schema/conf_v0_schema.py, tests/test_addc.py
Lately I keep hitting hosts that have "bogus" interfaces, stuff like "docker0" that are not suitable for including in the DNS records of the DC. While one could configuring these statically if you know all "good" interfaces ahead of time I keep bumping into the fact that I don't - nor do I want to carefully examine every host. What I do know is stuff like `docker0` or `virbirX` are often not suitable.
Thus I'm adding some new options for the domain_settings section. Under the domain one can have "interfaces" and interfaces can contain any of "include_pattern" and "exclude_pattern". Both take regexes and filter as they are named.  This way I can just start doing stuff like setting:
```
"domain_settings": {
"sink": {
"realm": "DOMAIN1.SINK.TEST",
"short_domain": "DOMAIN1",
"admin_password": …
```
=> addc: dynamic interface filtering for provisioning

sambacc/schema/conf-v0.schema.json, sambacc/schema/conf-v0.schema.yaml, sambacc/schema/conf_v0_schema.py
Thanks to @anoopcs9 for pointing out some potentially confusing wording in the previous patches adding interfaces options include_pattern & exclude_pattern. Change 'system interfaces' to 'network interfaces'.
=> schema: improve wording in interfaces description field

.github/workflows/ci.yml
Eliminate github's warning ("Node.js 16 actions are deprecated") by upgrading to 'checkout@v4'.
=> workflows: upgrade to checkout@v4

.github/workflows/ci.yml
There's a consistent failure on the f38 build that causes the other builds to terminate early. Unset the fail-fast option to allow the other jobs to run while we investigate the failure and/or wait for f40.
=> workflows: disable fail-fast option for distro matrix

.github/mergify.yml, .github/workflows/ci.yml
Fedora 40 has been out for a few weeks. Update the test matrix to remove
the EOL fedora 38 and use fedora 40.
=> workflows: update text matrix to use fedora 40

tox.ini
Add descriptions to our various tox environments and make `tox list` look nice and provide useful hints.
Clean up an old workaround.
=> tox: minor tox configuration updates

sambacc/ctdb.py
A minor cleanup in the ctdb.py module. If we are going to use a closure we might as well go all the way with it.
=> sambacc: simplify the closure function writing ctdb config

sambacc/commands/cli.py, sambacc/config.py, sambacc/ctdb.py, sambacc/leader.py, sambacc/opener.py, sambacc/simple_waiter.py, sambacc/smbconf_api.py, tox.ini
Depends on: #118 
Add some docstrings and then update the version of the black formatter tool our tox envs are allowed to use.
=> update black version

sambacc/commands/dcmain.py, sambacc/commands/main.py, sambacc/commands/skips.py, tests/test_skips.py
Depends on: #119
Previously, sambacc had the `--skip-if-file=` command line option that
would skip running a command if a named file exists. I have a need for
doing something similar for environment variable contents. In order to
avoid needing to add a plethora of new --skip-if-x type options over
time, add a more generic `--skip-if=` option and have the value contain
an initial prefix like `file:` or `env:` that determines how the rest of
the value will be parsed and how the skip will be determined (or not).
Deprecate `--skip-if-file`.
Maybe it's a case of over engineering, but at least it's easy to unit
test.
Examples:
* `--skip-if=env:CHAT==yes`, if the environment variable `CHAT` contains
a value equal to "yes" the command will be skipped
* `--skip-if=file:/foo/bar` if the file …
=> commands: add new generic --skip-if command line options 

sambacc/commands/main.py
Include the ability to skip if a file is missing with a `!` char (tersely) in the help string of the `--skip-if` option.
=> commands: tweak --skip-if help string

sambacc/commands/ctdb.py, sambacc/commands/main.py, sambacc/rados_opener.py, tests/test_rados_opener.py
Depends on #122
Add support to rados module to implement the ClusterMeta protocol.
Add rados support to sambacc ctdb commands.
Add a helpful CLI option for getting node number from env (it's a bit unrelated to the rados focus of the other changes but I didn't want to file a whole PR just for that).
=> Extend support for ctdb cluster meta stored in ceph rados

sambacc/commands/ctdb.py, sambacc/ctdb.py
Add some additional options to the ctdb related sambacc commmands. The --write-node option in particular is a bit hacky but it helps me get on with prototyping samba+ctdb in containers under ceph.
=> Add some more ctdb related hacks

sambacc/commands/ctdb.py, sambacc/rados_opener.py, sambacc/samba_cmds.py
Depends on: #124 
Add a new `ctdb-rados-mutex` subcommand that is meant to serve as a direct wrapper around the `ctdb_mutex_ceph_rados_helper` command that "understands" some of the
intended container workflow and argument style AND prevent issues in ctdb configuration where the cephx entity names are going to vary.
=> ctdb: wrap reclock script

sambacc/commands/ctdb.py, sambacc/commands/run.py, sambacc/ctdb.py
Add a `samba-container ctdb-list-nodes` command that emits a "nodes file" content to the stdout of the process.
Add hooks to set up a ctdb "nodes_cmd" config file option that tells ctdb to execute a command to fetch the nodes rather than read a file.
Also add a `--wait-for=ctdb` option to avoid starting certain services before ctdb is available and causing unnecessary container restarts.
=> ctdb: nodes list command, wait for ctdb option

sambacc/ctdb.py
Add a loop that tries the `ctdb reloadnodes` command after an increasing delay. This is an attempt to fix a condition where ctdbd is apparently not ready to handle the `ctdb reloadnodes` command. In this case the command would be run, but fail and an exception would be raised in the monitor_cluster_meta_changes function would raise an exception. This would be caught by the command-level retry loop. However, this command-level retry loop will simply re-run monitor_cluster_meta_changes and this function now no longer has the same initial clustermeta state and has effectively "forgotten" that it needs to run reloadnodes.  This new retry loop adds a level of error handling inside the monitor_cluster_meta_changes function so that we will retry with a bounded number of attempts.
=> sambacc: add a retry loop to ctdb.monitor_cluster_meta_changes

sambacc/commands/initialize.py, sambacc/config.py, sambacc/ctdb.py
Allow sambacc to set up the public_addresses file for ctdb and enable the required event script for basic ip failover.
=> Add simple support for ctdb public addrs

sambacc/ctdb.py
The samba wiki and documentation clearly state that the list of interfaces should be comma separated but I incorrectly joined them with spaces. Fix this and one other small suboptimal line in the same function.
=> sambacc: fix constructing interface list for ctdb public_addresses

tests/container/build.sh
I've been using this patch on an entitled rhel9 node, with epel installed. Calling the script like this does produce a build.
```
export SAMBACC_BUILD_TASKS="task_sys_deps task_py_build task_rpm_build"
export SAMBACC_BUILD_DIR=/tmp/sambacc-build
export SAMBACC_DISTNAME=rhel9
export SAMBACC_REPO_URL="https://github.com/ibmstorage/sambacc"
sh sambacc/tests/container/build.sh
```
=> add rhel support to rpm builds

sambacc/commands/ctdb.py
Updated the hostname lookup function to support multi-homed systems and mixed IPv4/IPv6 environments by using `socket.getaddrinfo`. 
This change removes the previous loopback filtering hack, now explicitly filtering loopback addresses and prioritizing IPv4 addresses where available. Improved error handling for cases with no valid IP addresses found.
Fixes: https://github.com/samba-in-kubernetes/sambacc/issues/136
=> ctdb: improve hostname lookup for ctdb nodes

sambacc/commands/ctdb.py
I was shown a cluster that had failed to communicate with rados during the `ctdb-must-have-node` command, after it had at least correctly read "nothing".
Add a retry loop (with limit) to the command to make it robust against spurious errors.
=> add retry loop to ctdb-must-have-node command

sambacc/config.py, tests/test_ctdb.py
There is too much information with the `log level` explicitily set to DEBUG for _ctdbd_ flooding the log file destination. Similarly `script log level` option might also spit out more when set to DEBUG. Instead of removing the options altogether we change the sambacc defaults from DEBUG to NOTCE and ERROR respectively for `log level` and `script log level` options as specified in man [ctdb.conf(5)](https://ctdb.samba.org/manpages/ctdb.conf.5.html).
=> ctdb: Leave CTDB log levels at their original defaults

sambacc/ctdb.py
Added support for the GONE state in _entry_to_node to exclude nodes no longer part of the cluster.
=> ctdb: handle nodes with "GONE" state when listing CTDB nodes

.github/mergify.yml, .github/workflows/ci.yml
Fedora 41 has been out for some weeks now. Update the test matrix to remove Fedora 39 and use fedora 41.
=> workflows: update test matrix to use fedora 41

tests/container/Containerfile
Forgot to update this when we updated the workflows file.
=> tests/container: update base image to fedora 41

sambacc/commands/ctdb.py
It seems that a recent mypy release is now determining that certain family types (not AF_INET, or AF_INET6) may return an address tupe with the first element type being an int rather than a str. The (expanded) revealed type is:
```
tuple[
socket.AddressFamily,
socket.SocketKind,
builtins.int,
builtins.str,
Union[
tuple[builtins.str, builtins.int],
tuple[builtins.str, builtins.int, builtins.int, builtins.int],
tuple[builtins.int, builtins.bytes]
]
]
```
This change ensures that we only check the family values we care about and use a type assertion for those families where we expect the address value to be a str.
FWIW I could not find any documentation for what families have an integer in the first element of the addr tuple. Looking at the python sources it seems like it could be …
=> commands: fix a mypy failure in the ctdb commands module

sambacc/commands/ctdb.py, sambacc/samba_cmds.py
Depends on: https://gitlab.com/samba-team/samba/-/merge_requests/4002
When the ctdb ceph rados mutex helper tool supports the -R option to
skip registering the helper as a ceph service - do so.
This avoids confusion on the ceph side as the helper will act more like
a typical rados client than something on the level of an OSD or MDS.
=> ctdb: skip mutex helper service registration

sambacc/commands/initialize.py, sambacc/textfile.py
On some newer OS releases, standard config files are installed in /usr/etc with site changes to copies in /etc.
That results in the following startup failure:
Traceback (most recent call last):
File "/usr/bin/samba-container", line 8, in <module>
sys.exit(main())
^^^^^^
File "sambacc/commands/main.py", line 231, in main
cfunc(CommandContext(cli))
File "sambacc/commands/run.py", line 75, in run_container
init_container(ctx)
File "sambacc/commands/initialize.py", line 116, in init_container
cmds[step_name].cmd_func(ctx)
File "sambacc/commands/initialize.py", line 38, in _import_nsswitch
nss.read()
File "sambacc/textfile.py", line 28, in read
with open(self.path) as f:
^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/etc/nsswitch.conf'
This changes the initialization …
=> commands: handle /usr/etc/nsswitch.conf

sambacc/commands/join.py, sambacc/config.py, sambacc/join.py, tests/test_join.py
Add basic support for joining to AD using Offline Domain Join blobs.
=> Add basic ODJ support

extras/python-sambacc.spec, tests/container/build.sh
Allow a vendor dist suffix field in the spec file.
It can be passed to the build script with the VENDOR_DIST_SUFFIX env var
set to a value. Then it will pass that along to the rpm build as the
vendordist value to be suffixed to the release ver.
=> rpm: vendor dist suffix

sambacc/commands/config.py
When the `samba-container config-update --watch` command is run on a CTDB enabled server we avoid updating the local config unless the node is the ctdb leader. However, the update function was returning the current config which the watch loop assigned to the previous var, meaning that the current and previous config would be equal on future trips around the loop. Therefore once the node became the leader it would not update the config even if it differed from the config in samba. This is a problem on start up because the loop initially runs before ctdb is ready and the node leadership is not known. Change it so that when the node is not a leader it returns None and "unsets" the previous config. This could lead to extra unneeded updates but should avoid missing updates that are needed.
=> commands: invalidate cached config when node is not ctdb leader

.github/mergify.yml
Mergify rules doesn't check the status of pull requests before adding the "priority-review" label. In addition to the existing rules it only makes sense to add the label if the pull request is in open state.
=> mergify: Restrict the addition of "priority-review" label

tox.ini
Add a tox environment that runs black to format the code rather than just checking it. This environment is not run automatically but it provided for developers as a means to format the code in a way that is consistent with this project's configuration.
=> tox.ini: add a rule to reformat source code

docs/release-process.md
Update the PyPI section of the release process doc to use a path that is more consistent with the sections above. Remove a reference to a username prompt as newer versions of twine no longer prompt for a username and require a token.
=> docs: update pypi section in the release process doc
